Repository bangumi/server-private, pull requests merged in 2023-01, with the labels that each got.

#30 fix: hidden topic
  lib/auth/rule.ts
  lib/orm/entity/group.ts
  lib/orm/index.ts
  lib/rest/private/routes/topic.test.ts
  lib/rest/private/routes/topic.ts
  lib/topic.ts
  lib/topic/__snapshots__/index.test.ts.snap
  lib/topic/display.ts
  lib/topic/index.test.ts
  lib/topic/index.ts
Labels: size/XL

#32 feat: new api to edit group reply
  lib/rest/private/index.ts
  lib/rest/private/routes/post.test.ts
  lib/rest/private/routes/post.ts
Labels: size/M

#34 chore: switch to `@node-rs/bcrypt` for better performance
  lib/auth/index.ts
  package.json
  yarn.lock
Labels: size/XS

#46 feat: upload subject cover
  .eslintrc.cjs
  .gitignore
  config.example.yaml
  lib/config.ts
  lib/image/base.ts
  lib/image/fs.test.ts
  lib/image/fs.ts
  lib/image/index.ts
  lib/image/s3.ts
  lib/orm/entity/subject.ts
  lib/orm/index.ts
  lib/rest/demo/editor.ts
  lib/rest/hooks/pre-handler.ts
  lib/rest/private/routes/wiki/fixtures/subject.jpg
  lib/rest/private/routes/wiki/fixtures/subject.webp
  lib/rest/private/routes/wiki/subject.test.ts
  lib/rest/private/routes/wiki/subject.ts
  lib/server.ts
  lib/services/base.ts
  lib/services/imaginary.ts
  lib/subject/index.ts
  lint-staged.config.js
  package.json
  templates/upload-cover.liquid
  tests/utils.ts
  yarn.lock
Labels: size/XL
