Repository bangumi/server-private, pull requests merged in 2024-09, with the labels that each got.

#713 fix: book date parsing
  lib/subject/date.test.ts
  lib/subject/date.ts
  lib/subject/index.ts
Labels: size/S

#714 Fix subject order
  lib/subject/date.test.ts
  lib/subject/date.ts
  lib/subject/index.ts
  lib/subject/platform.ts
  lib/utils/date.ts
Labels: size/S

#677 feat(graphql): add Character & Person & Subject relations
  bin/fix-date.ts
  lib/graphql/schema.gen.graphql
  lib/graphql/types/character.ts
  lib/graphql/types/person.ts
  lib/graphql/types/subject.ts
  lib/orm/entity/character.ts
  lib/orm/entity/index.ts
  lib/orm/entity/person.ts
  lib/orm/entity/subject-relation.ts
  lib/orm/entity/subject.ts
  lib/orm/index.ts
  lib/orm/unused/ChiiCrtCastIndex.ts.tmp
  lib/orm/unused/ChiiCrtSubjectIndex.ts.tmp
  lib/orm/unused/ChiiPersonCsIndex.ts.tmp
  lib/orm/unused/ChiiSubjectFields.ts.tmp
  lib/subject/date.ts
  lib/subject/index.test.ts
  lib/subject/index.ts
  tests/__snapshots__/server.test.ts.snap
  tests/graphql/README.md
  tests/graphql/__snapshots__/character.test.ts.snap
  tests/graphql/__snapshots__/me.test.ts.snap
  tests/graphql/__snapshots__/person.test.ts.snap
  tests/graphql/__snapshots__/subject.test.ts.snap
  tests/graphql/character.test.ts
  tests/graphql/me.test.ts
  tests/graphql/person.test.ts
  tests/graphql/subject.test.ts
Labels: size/XXL

#718 feat(graphql): add subject topics
  lib/graphql/schema.gen.graphql
  lib/graphql/types/subject.ts
  lib/graphql/types/user.ts
  lib/orm/entity/group.ts
  lib/orm/entity/subject.ts
  lib/orm/unused/ChiiSubjectTopics.ts.tmp
  lib/server.ts
  tests/graphql/__snapshots__/subject.test.ts.snap
  tests/graphql/subject.test.ts
Labels: size/M

#724 refactor: make graphql schema first
  .eslintrc.cjs
  .graphqlrc.yml
  codegen.ts
  lib/graphql/__generated__/resolvers.ts
  lib/graphql/context.ts
  lib/graphql/resolvers/character.ts
  lib/graphql/resolvers/person.ts
  lib/graphql/resolvers/subject.ts
  lib/graphql/schema.gen.graphql
  lib/graphql/schema.graphql
  lib/graphql/schema.ts
  lib/graphql/types/character.ts
  lib/graphql/types/common.ts
  lib/graphql/types/index.ts
  lib/graphql/types/person.ts
  lib/graphql/types/subject.ts
  lib/graphql/types/user.ts
  lib/logger.ts
  lib/orm/index.ts
  lib/server.ts
  package.json
  pnpm-lock.yaml
  tests/graphql/__snapshots__/subject.test.ts.snap
  tsconfig.json
Labels: size/XXL

#725 feat: support person edit
  lib/orm/entity/rev.ts
  lib/rev/ep.ts
  lib/subject/index.test.ts
  lib/subject/index.ts
  routes/private/routes/wiki/index.ts
  routes/private/routes/wiki/person/index.spec.ts
  routes/private/routes/wiki/person/index.ts
  routes/private/routes/wiki/subject/index.ts
  routes/private/routes/wiki/subject/mgr.ts
Labels: size/XL

#726 feat: recent person change list
  lib/orm/entity/rev.ts
  lib/rev/ep.ts
  routes/admin/ep.ts
  routes/private/routes/wiki/index.test.ts
  routes/private/routes/wiki/index.ts
Labels: size/S

#735 build: upgrade fastify to v5
  bin/main.ts
  lib/graphql/ui.ts
  lib/server.ts
  package.json
  pnpm-lock.yaml
  routes/index.ts
  routes/swagger.ts
  routes/type.ts
Labels: size/S

#738 refactor: migrate oauth to drizzle orm
  drizzle/schema.ts
  lib/auth/index.ts
  lib/orm/entity/index.ts
  lib/orm/entity/oauth-client.ts
  lib/orm/entity/user.ts
  lib/orm/index.ts
  lib/utils/index.ts
  routes/demo/token/index.ts
  routes/oauth/index.test.ts
  routes/oauth/index.ts
  tests/utils.ts
Labels: size/XL
