Repository bangumi/server-private, pull requests merged in 2024-12, with the labels that each got.

#843 fix: filter offprint field
  lib/subject/type.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/subject.ts
  routes/private/routes/user.ts
  routes/private/routes/wiki/subject/ep.ts
Labels: size/S

#844 fix: change infobox back to array
  lib/types/convert.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/character.test.ts.snap
  routes/private/routes/__snapshots__/person.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/__snapshots__/topic.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
Labels: size/XXL

#845 refactor: subject comments
  drizzle/orm.ts
  drizzle/schema.ts
  lib/graphql/schema.ts
  lib/orm/index.ts
  lib/services/turnstile.ts
  lib/topic/display.ts
  lib/topic/index.test.ts
  lib/topic/index.ts
  lib/topic/type.ts
  lib/types/convert.ts
  lib/types/examples.ts
  lib/types/fetcher.ts
  lib/types/req.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/__snapshots__/topic.test.ts.snap
  routes/private/routes/post.test.ts
  routes/private/routes/post.ts
  routes/private/routes/subject.test.ts
  routes/private/routes/subject.ts
  routes/private/routes/topic.test.ts
  routes/private/routes/topic.ts
  routes/res.ts
Labels: size/XXL

#846 feat: extra nameCN for character & person
  lib/types/convert.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/character.test.ts.snap
  routes/private/routes/__snapshots__/person.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
Labels: size/S

#847 feat: add user homepage layout
  lib/types/convert.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
  routes/res.ts
Labels: size/M

#849 fix: html unescape comments/posts
  drizzle/schema.ts
Labels: size/S

#850 fix: tmp disable field homepage
  drizzle/schema.ts
  lib/types/convert.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
Labels: size/XS

#851 feat: add api subject recs
  drizzle/orm.ts
  drizzle/schema.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/subject.test.ts
  routes/private/routes/subject.ts
  routes/res.ts
Labels: size/M

#852 fix: avoid refresh token in parallel
  routes/oauth/index.ts
Labels: size/M

#853 fix: responsive for oauth page
  templates/layout.liquid
  templates/oauth/authorize.liquid
  templates/partial/header.liquid
Labels: size/M

#854 fix: oauth page padding
  templates/oauth/authorize.liquid
Labels: size/M

#855 fix: set max-width on oauth page
  templates/oauth/authorize.liquid
Labels: size/XS

#857 fix: response positions for personWorks & subjectStaffs
  lib/types/convert.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/person.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/person.ts
  routes/private/routes/subject.ts
  routes/res.ts
Labels: size/M

#858 fix: duplicate character in person casts
  routes/private/routes/person.ts
Labels: size/XS

#859 feat: add subject infobox summary
  lib/subject/infobox.ts
  lib/types/convert.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/character.test.ts.snap
  routes/private/routes/__snapshots__/person.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
Labels: size/S

#861 fix: use transaction for meta tags update
  lib/subject/index.ts
Labels: size/XS

#862 fix: countDistinct instead of count groupby
  lib/types/fetcher.ts
  routes/private/routes/__snapshots__/person.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/person.ts
  routes/private/routes/subject.ts
Labels: size/XS

#864 feat: add collection type to subject comment
  lib/types/convert.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
Labels: size/XS

#860 feat: timeline api
  bin/mq.ts
  build.mjs
  docs/timeline.md
  drizzle/orm.ts
  drizzle/schema.ts
  event/timeline.ts
  event/type.ts
  lib/config.ts
  lib/like.ts
  lib/openapi/index.ts
  lib/response.ts
  lib/timeline/cache.ts
  lib/timeline/image.ts
  lib/timeline/inbox.ts
  lib/timeline/memo.ts
  lib/timeline/type.ts
  lib/timeline/user.ts
  lib/types/convert.ts
  lib/types/fetcher.ts
  lib/types/res.ts
  package.json
  pnpm-lock.yaml
  routes/__snapshots__/index.test.ts.snap
  routes/private/index.ts
  routes/private/routes/__snapshots__/timeline.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
  routes/private/routes/timeline.test.ts
  routes/private/routes/timeline.ts
  routes/private/routes/topic.ts
  routes/private/routes/user.test.ts
  routes/private/routes/user.ts
  routes/res.ts
Labels: size/XXL

#825 feat: add user network servies
  lib/types/convert.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
  routes/private/routes/user.ts
Labels: size/S

#831 feat: add api subject reviews
  drizzle/orm.ts
  drizzle/schema.ts
  lib/types/convert.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/subject.ts
  routes/res.ts
Labels: size/L

#865 feat: cache subject & slim subject
  bin/mq.ts
  docs/timeline.md
  drizzle/schema.ts
  event/subject.ts
  lib/const.ts
  lib/subject/cache.ts
  lib/subject/index.test.ts
  lib/subject/index.ts
  lib/subject/type.ts
  lib/timeline/image.ts
  lib/timeline/inbox.ts
  lib/timeline/memo.ts
  lib/timeline/user.ts
  lib/trending/subject.ts
  lib/types/convert.ts
  lib/types/fetcher.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/trending.ts
Labels: size/L
