Repository bangumi/server-private, pull requests merged in 2024-11, with the labels that each got.

#804 fix: split subject meta tags with space
  lib/types/convert.ts
Labels: size/XS

#813 build: upgrade nodejs-lts to v22
  .github/actions/setup-js-env/action.yaml
  Dockerfile
  package.json
  pnpm-lock.yaml
Labels: size/XS

#815 fix: PersonWikiInfo typo
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/wiki/person/index.ts
Labels: size/S

#826 feat: add arg since to getUserSubjectCollections
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/user.ts
Labels: size/XS

#828 feat: add cron to update trending subjects
  bin/cron.ts
  build.mjs
  drizzle/schema.ts
  package.json
  pnpm-lock.yaml
  routes/private/routes/user.ts
  tasks/heartbeat.ts
  tasks/trending.ts
Labels: size/L

#830 feat: add trending subject api
  lib/openapi/index.ts
  lib/trending/subject.ts
  lib/trending/type.ts
  lib/types/fetcher.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/index.ts
  routes/private/routes/trending.ts
  tasks/trending.ts
Labels: size/L

#832 chore: add more logs for cron
  bin/cron.ts
  tasks/trending.ts
Labels: size/XS

#833 feat: add api for single collection item
  drizzle/orm.ts
  drizzle/schema.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
  routes/private/routes/user.test.ts
  routes/private/routes/user.ts
Labels: size/XXL

#835 fix: cron trending dateline
  lib/trending/subject.ts
  lib/trending/type.ts
Labels: size/S

#836 feat: api for episode colleciton
  drizzle/orm.ts
  drizzle/schema.ts
  lib/subject/type.ts
  lib/types/convert.ts
  lib/types/fetcher.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/__snapshots__/topic.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
  routes/private/routes/subject.ts
  routes/private/routes/user.test.ts
  routes/private/routes/user.ts
Labels: size/L

#837 fix: argument minimum for since
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/user.ts
Labels: size/XS
