Repository bangumi/server-private, pull requests merged in 2024-10, with the labels that each got.

#743 fix: adjust oauth token expires
  routes/oauth/index.ts
Labels: size/XS

#717 style: upgrade to eslint v9
  .eslintrc.cjs
  bin/main.ts
  eslint.config.mjs
  eslint/index.mjs
  eslint/no-relative-parent-import.mjs
  lib/auth/authcode.ts
  lib/config.ts
  lib/graphql/__generated__/resolvers.ts
  lib/graphql/context.ts
  lib/image/base.ts
  lib/orm/index.ts
  lib/utils/date.ts
  package.json
  pnpm-lock.yaml
  routes/admin/index.ts
  routes/demo/index.ts
  routes/hooks/pre-handler.ts
  routes/hooks/rate-limit.ts
  routes/oauth/index.test.ts
  routes/oauth/index.ts
  routes/private/routes/login.ts
  routes/private/routes/post.ts
  routes/private/routes/topic.ts
  routes/private/routes/user.ts
  routes/private/routes/wiki/index.ts
  routes/private/routes/wiki/person/index.ts
  routes/private/routes/wiki/subject/ep.ts
  routes/private/routes/wiki/subject/image.ts
  routes/private/routes/wiki/subject/index.ts
  routes/private/routes/wiki/subject/mgr.ts
  routes/swagger.ts
  scripts/build-common.mjs
  tsconfig.json
  vendor/node-cache.ts
  vitest.config.ts
Labels: size/XL

#748 build: remove tsx from runtime
  bin/main.ts
  build.mjs
  eslint/no-relative-parent-import.mjs
  etc/base.dockerfile
  etc/final.dockerfile
  lib/config.ts
  package.json
  pnpm-lock.yaml
  routes/hooks/pre-handler.ts
  vitest.config.ts
Labels: size/M

#749 feat: support update new metaTags
  drizzle/db.ts
  drizzle/new/0000_flaky_bruce_banner.sql
  drizzle/new/meta/0000_snapshot.json
  drizzle/new/meta/_journal.json
  drizzle/new/relations.ts
  drizzle/new/schema.ts
  drizzle/schema.ts
  eslint.config.mjs
  lib/const.ts
  lib/subject/index.test.ts
  lib/subject/index.ts
  lib/wiki.ts
  routes/private/routes/wiki/person/index.ts
  routes/private/routes/wiki/subject/index.ts
  routes/private/routes/wiki/subject/subject.test.ts
  tsconfig.json
Labels: size/XXL

#752 fix: return resUser for comments
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/post.ts
  routes/private/routes/subject.test.ts
Labels: size/M

#754 fix: return type for SubjectInterestComment
  routes/private/routes/post.ts
Labels: size/XS

#755 fix: get subject comments order by lastTouch desc
  lib/orm/entity/subject.ts
  routes/private/routes/post.ts
Labels: size/XS

#753 feat: add api for user collections summary
  drizzle/new/schema.ts
  drizzle/schema.ts
  lib/openapi/index.ts
  lib/orm/unused/ChiiSubjectInterests.ts.tmp
  lib/subject/collection.ts
  lib/subject/platform.ts
  lib/types/res.ts
  package.json
  pnpm-lock.yaml
  routes/private/index.ts
  routes/private/routes/__snapshots__/collection.test.ts.snap
  routes/private/routes/collection.test.ts
  routes/private/routes/collection.ts
  routes/private/routes/wiki/subject/index.ts
Labels: size/XXL

#757 fix: more restrict for collection summary
  routes/private/routes/__snapshots__/collection.test.ts.snap
  routes/private/routes/collection.ts
Labels: size/XL

#761 feat: api for user collection subjects
  drizzle/orm.ts
  drizzle/schema.ts
  lib/auth/session.test.ts
  lib/subject/index.ts
  lib/topic/index.ts
  lib/types/convert.ts
  lib/types/examples.ts
  lib/types/res.ts
  lib/types/util.ts
  routes/demo/index.ts
  routes/oauth/index.test.ts
  routes/oauth/index.ts
  routes/private/routes/__snapshots__/collection.test.ts.snap
  routes/private/routes/collection.test.ts
  routes/private/routes/collection.ts
  routes/private/routes/login.ts
  routes/private/routes/post.ts
  routes/private/routes/topic.ts
  routes/private/routes/user.ts
  routes/private/routes/wiki/person/index.ts
  routes/private/routes/wiki/subject/ep.ts
  routes/private/routes/wiki/subject/image.ts
  routes/private/routes/wiki/subject/index.ts
Labels: size/XXL

#767 feat: cloudflare turnstile verify page
  routes/private/routes/user.ts
  templates/turnstile.liquid
Labels: size/S

#762 feat: add character & person & index to user collection summary
  drizzle/orm.ts
  drizzle/schema.ts
  lib/auth/session.test.ts
  lib/subject/collection.ts
  lib/subject/type.ts
  lib/topic/index.ts
  lib/types/convert.ts
  lib/types/res.ts
  routes/demo/index.ts
  routes/oauth/index.test.ts
  routes/oauth/index.ts
  routes/private/routes/__snapshots__/collection.test.ts.snap
  routes/private/routes/collection.test.ts
  routes/private/routes/collection.ts
  routes/private/routes/login.ts
  routes/private/routes/post.ts
  routes/private/routes/topic.ts
  routes/private/routes/user.ts
  routes/private/routes/wiki/subject/image.ts
  vitest.config.ts
Labels: size/XXL

#770 fix: rate limit checks
  lib/topic/index.ts
  routes/hooks/rate-limit.ts
  routes/private/routes/post.ts
  routes/private/routes/topic.ts
Labels: size/S

#774 feat: add api for user indexes
  drizzle/orm.ts
  routes/private/routes/__snapshots__/collection.test.ts.snap
  routes/private/routes/collection.test.ts
  routes/private/routes/collection.ts
Labels: size/M

#781 feat: add api for user friends
  drizzle/orm.ts
  drizzle/schema.ts
  lib/orm/index.ts
  lib/types/convert.ts
  lib/types/fetcher.ts
  lib/types/res.ts
  routes/private/index.ts
  routes/private/routes/__snapshots__/topic.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
  routes/private/routes/collection.ts
  routes/private/routes/login.ts
  routes/private/routes/post.ts
  routes/private/routes/topic.test.ts
  routes/private/routes/topic.ts
  routes/private/routes/user.test.ts
  routes/private/routes/user.ts
  routes/private/routes/wiki/index.test.ts
  routes/private/routes/wiki/index.ts
  routes/private/routes/wiki/person/index.ts
  routes/private/routes/wiki/subject/ep.ts
  routes/private/routes/wiki/subject/index.ts
  routes/res.ts
  tests/utils.ts
Labels: size/L

#784 feat: add subject and relation api
  drizzle/orm.ts
  drizzle/schema.ts
  lib/types/convert.ts
  lib/types/fetcher.ts
  routes/private/index.ts
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/__snapshots__/subjectPost.test.ts.snap
  routes/private/routes/collection.ts
  routes/private/routes/subject.test.ts
  routes/private/routes/subject.ts
  routes/private/routes/subjectPost.test.ts
Labels: size/XL

#786 feat: add type SlimUser
  lib/types/convert.ts
  lib/types/res.ts
  routes/private/routes/__snapshots__/user.test.ts.snap
  routes/res.ts
Labels: size/S

#789 feat: oauth scope
  lib/scope.ts
  routes/oauth/index.ts
  templates/oauth/authorize.liquid
Labels: size/M

#788 feat: api for subject related characters & persons
  drizzle/orm.ts
  drizzle/schema.ts
  lib/types/fetcher.ts
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/subject.test.ts
  routes/private/routes/subject.ts
Labels: size/L

#794 feat: api for subject episodes
  drizzle/orm.ts
  drizzle/schema.ts
  lib/types/convert.ts
  lib/types/res.ts
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/subject.test.ts
  routes/private/routes/subject.ts
  routes/res.ts
Labels: size/M

#795 chore: api for user & organize user apis
  drizzle/schema.ts
  lib/types/convert.ts
  lib/types/fetcher.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/demo/index.ts
  routes/private/index.ts
  routes/private/routes/__snapshots__/collection.test.ts.snap
  routes/private/routes/__snapshots__/login.test.ts.snap
  routes/private/routes/__snapshots__/subjectPost.test.ts.snap
  routes/private/routes/__snapshots__/topic.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
  routes/private/routes/collection.test.ts
  routes/private/routes/collection.ts
  routes/private/routes/login.ts
  routes/private/routes/misc.test.ts
  routes/private/routes/misc.ts
  routes/private/routes/post.test.ts
  routes/private/routes/post.ts
  routes/private/routes/topic.test.ts
  routes/private/routes/topic.ts
  routes/private/routes/user.test.ts
  routes/private/routes/user.ts
  routes/private/routes/wiki/subject/image.ts
Labels: size/XXL
