Repository bangumi/server-private, pull requests merged in 2025-02, with the labels that each got.

#972 chore: clean unused code
  lib/orm/index.ts
  routes/private/routes/wiki/person/index.ts
Labels: size/M

#973 chore: fix import schema
  drizzle/db.ts
  lib/subject/index.test.ts
  lib/subject/index.ts
Labels: size/XS

#975 fix: reply for topic detail
  lib/types/convert.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/episode.test.ts.snap
  routes/private/routes/episode.ts
  routes/private/routes/group.ts
  routes/private/routes/subject.ts
  routes/schemas.ts
Labels: size/L

#976 bump: 0.12.4
  package.json
Labels: size/XS

#977 ci: use changlog generator from upstream
  .github/workflows/release-github.yaml
Labels: size/XS

#978 fix: make creator non optional for topic
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
Labels: size/XS

#979 style: disable some liquid template check
  .theme-check.yml
  templates/login.liquid
Labels: size/XS

#980 feat: add api for post detail
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/group.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/group.test.ts
  routes/private/routes/group.ts
  routes/private/routes/subject.test.ts
  routes/private/routes/subject.ts
  routes/schemas.ts
Labels: size/L

#981 bump: 0.12.7
  package.json
Labels: size/XS

#982 fix: filter group member moderator
  routes/private/routes/__snapshots__/group.test.ts.snap
  routes/private/routes/group.ts
Labels: size/XS

#947 feat: handle more mq events for cache
  bin/mq.ts
  event/blog.ts
  event/group.ts
  event/index.ts
  lib/blog/cache.ts
  lib/group/cache.ts
  lib/index/cache.ts
Labels: size/M

#984 fix: missing creator for top level reply
  routes/private/routes/group.ts
  routes/private/routes/subject.ts
Labels: size/XS

#985 fix: remove wrong exclusiveMinimum in api spec
  routes/__snapshots__/index.test.ts.snap
  routes/admin/ep.ts
  routes/admin/index.ts
  routes/demo/token/index.ts
  routes/private/routes/episode.ts
  routes/private/routes/subject.ts
  routes/private/routes/wiki/person/index.ts
  routes/private/routes/wiki/subject/ep.ts
  routes/private/routes/wiki/subject/image.ts
  routes/private/routes/wiki/subject/index.ts
  templates/token/create.liquid
Labels: size/M

#986 fix: turnstile driver with secret key
  lib/services/turnstile.ts
  routes/private/routes/auth.ts
Labels: size/XS

#987 fix: cache for episode
  event/subject.ts
  lib/subject/cache.ts
Labels: size/XS

#988 refactor: rename subject schema fields
  drizzle/schema.ts
  lib/subject/index.test.ts
  lib/types/convert.ts
  lib/types/fetcher.ts
  routes/private/routes/collection.ts
  routes/private/routes/user.ts
Labels: size/M

#989 fix: subject interest privacy
  drizzle/schema.ts
  lib/subject/index.test.ts
  lib/subject/type.ts
  lib/types/convert.ts
  lib/types/fetcher.ts
  lib/user/stats.ts
  routes/private/routes/subject.ts
  routes/private/routes/user.ts
Labels: size/S

#942 feat: wiki subject batch edit episodes api
  lib/rev/ep.test.ts
  lib/rev/ep.ts
  lib/types/common.ts
  lib/types/req.ts
  lib/utils/date.ts
  lib/utils/index.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/wiki/subject/ep.test.ts
  routes/private/routes/wiki/subject/ep.ts
  routes/private/routes/wiki/subject/index.ts
  routes/private/routes/wiki/subject/subject.test.ts
  routes/schemas.ts
Labels: size/XL

#990 bump: 0.12.9
  package.json
Labels: size/XS

#992 Create codeql.yml
  .github/workflows/codeql.yaml
Labels: size/S

#1004 feat: add general comment functions
  drizzle/schema.ts
  lib/comment.ts
  lib/like.ts
  lib/types/req.ts
  lib/utils/rate-limit/index.ts
  routes/__snapshots__/index.test.ts.snap
  routes/hooks/rate-limit.ts
  routes/private/routes/episode.ts
  routes/schemas.ts
Labels: size/L

#1005 chore: minor fixes for comment
  lib/comment.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/episode.ts
Labels: size/S

#1006 feat: add comment apis
  event/timeline.ts
  lib/timeline/item.ts
  lib/types/fetcher.ts
  lib/user/cache.ts
  lib/user/utils.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/blog.test.ts
  routes/private/routes/blog.ts
  routes/private/routes/character.ts
  routes/private/routes/episode.ts
  routes/private/routes/misc.ts
  routes/private/routes/person.ts
  routes/private/routes/timeline.ts
  routes/private/routes/user.ts
Labels: size/XXL

#1008 ci: use latest corepack
  .github/actions/setup-js-env/action.yaml
Labels: size/XS

#1009 build: use latest corepack in docker
  Dockerfile
Labels: size/XS

#1010 feat: add timeline writer
  lib/timeline/memo.ts
  lib/timeline/type.ts
  lib/timeline/writer.ts
  lib/types/fetcher.ts
  routes/private/routes/timeline.ts
Labels: size/L

#1011 refactor: migrate notify to drizzle
  drizzle/db.ts
  drizzle/schema.ts
  lib/notify.ts
  routes/demo/index.ts
  routes/private/routes/group.ts
  routes/private/routes/misc.test.ts
  routes/private/routes/misc.ts
  routes/private/routes/subject.ts
Labels: size/L

#1012 fix: timeline writer static functions
  lib/timeline/writer.ts
  routes/private/routes/timeline.ts
Labels: size/XS

#1018 build: fix @confluentinc/kafka-javascript native module with pnpm@10
  .github/workflows/ci.yaml
  Dockerfile
  bin/mq.ts
  package.json
Labels: size/XS

#1019 refactor: migrate fetchUser & permission from old orm
  lib/auth/index.ts
  lib/graphql/schema.ts
  lib/orm/__snapshots__/orm.test.ts.snap
  lib/orm/index.ts
  lib/orm/orm.test.ts
  lib/types/convert.ts
  lib/types/res.ts
  lib/user/cache.ts
  lib/user/perm.test.ts
  lib/user/perm.ts
  lib/user/utils.ts
  routes/__snapshots__/index.test.ts.snap
  routes/admin/ep.ts
  routes/demo/index.ts
  routes/oauth/index.test.ts
  routes/oauth/index.ts
  routes/private/routes/__snapshots__/auth.test.ts.snap
  routes/private/routes/__snapshots__/blog.test.ts.snap
  routes/private/routes/__snapshots__/character.test.ts.snap
  routes/private/routes/__snapshots__/episode.test.ts.snap
  routes/private/routes/__snapshots__/friend.test.ts.snap
  routes/private/routes/__snapshots__/group.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/__snapshots__/timeline.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
  routes/private/routes/auth.ts
  routes/private/routes/wiki/subject/subject.test.ts
Labels: size/L

#1020 refactor: migrate fetchUsers from old orm
  lib/orm/index.ts
  lib/subject/index.ts
  lib/types/convert.ts
  lib/types/fetcher.ts
  routes/admin/ep.ts
  routes/private/routes/misc.ts
  routes/private/routes/wiki/subject/image.ts
  routes/private/routes/wiki/subject/index.ts
Labels: size/M

#1021 refactor: migrate notify from old orm
  routes/private/routes/misc.test.ts
Labels: size/XS

#1022 feat(kafka): handle timeline message
  bin/mq.ts
  lib/kafka.ts
  lib/timeline/kafka.ts
  lib/timeline/writer.ts
  routes/private/routes/timeline.ts
Labels: size/L

#1023 feat: add more field to timeline message
  lib/timeline/kafka.ts
  lib/timeline/writer.ts
  routes/private/routes/timeline.ts
Labels: size/M

#944 feat: add api for subject collect
  drizzle/schema.ts
  lib/subject/index.ts
  lib/subject/type.ts
  lib/subject/utils.ts
  lib/tag.ts
  lib/types/convert.ts
  lib/types/fetcher.ts
  lib/types/req.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/collection.ts
  routes/private/routes/episode.ts
  routes/private/routes/subject.ts
  routes/schemas.ts
Labels: size/XL

#1025 feat: add api for timeline replies
  lib/timeline/item.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/timeline.ts
Labels: size/M

#1026 bump: 0.13.3
  package.json
Labels: size/XS

#1027 feat: api for episode collect
  lib/subject/utils.ts
  lib/types/req.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/collection.ts
  routes/schemas.ts
Labels: size/M

#1028 bump: 0.13.4
  package.json
Labels: size/XS

#1029 bump: 0.14.0
  package.json
Labels: size/XS

#1030 fix: comment without state
  drizzle/schema.ts
  lib/comment.ts
  routes/private/routes/__snapshots__/blog.test.ts.snap
  routes/private/routes/__snapshots__/person.test.ts.snap
  routes/private/routes/blog.test.ts
  routes/private/routes/blog.ts
  routes/private/routes/character.ts
  routes/private/routes/episode.test.ts
  routes/private/routes/episode.ts
  routes/private/routes/person.test.ts
  routes/private/routes/person.ts
  routes/private/routes/timeline.ts
Labels: size/XL

#1031 fix: return slim subjects for trending
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/subject.ts
  routes/private/routes/trending.ts
Labels: size/XS

#1033 bump: 0.14.1
  package.json
Labels: size/XS

#1034 feat: init kafka producer on server start
  bin/main.ts
  lib/kafka.ts
Labels: size/XS

#1035 bump: 0.14.2
  package.json
Labels: size/XS

#1036 fix: wait kafka producer in onReady
  bin/main.ts
Labels: size/XS

#1037 fix: add source to kafka timeline message
  lib/timeline/writer.ts
  routes/private/routes/collection.ts
  routes/private/routes/timeline.ts
Labels: size/XS

#1038 fix: adjust rate limit for timeline and subject
  routes/hooks/rate-limit.ts
Labels: size/XS

#1041 refactor: organize import for drizzle
  drizzle/README.md
  drizzle/db.ts
  drizzle/index.ts
  lib/auth/index.ts
  lib/auth/session.test.ts
  lib/auth/session.ts
  lib/comment.ts
  lib/group/utils.ts
  lib/like.ts
  lib/notify.ts
  lib/rev/ep.test.ts
  lib/rev/ep.ts
  lib/subject/index.test.ts
  lib/subject/index.ts
  lib/subject/utils.ts
  lib/tag.ts
  lib/timeline/inbox.ts
  lib/timeline/item.ts
  lib/timeline/user.ts
  lib/timeline/writer.ts
  lib/topic/utils.ts
  lib/trending/subject.ts
  lib/types/convert.ts
  lib/types/fetcher.ts
  lib/user/perm.ts
  lib/user/stats.ts
  lib/user/utils.ts
  routes/demo/token/index.ts
  routes/oauth/index.test.ts
  routes/oauth/index.ts
  routes/private/routes/auth.test.ts
  routes/private/routes/blog.test.ts
  routes/private/routes/blog.ts
  routes/private/routes/character.ts
  routes/private/routes/collection.test.ts
  routes/private/routes/collection.ts
  routes/private/routes/episode.test.ts
  routes/private/routes/episode.ts
  routes/private/routes/friend.ts
  routes/private/routes/group.test.ts
  routes/private/routes/group.ts
  routes/private/routes/misc.test.ts
  routes/private/routes/misc.ts
  routes/private/routes/person.test.ts
  routes/private/routes/person.ts
  routes/private/routes/subject.test.ts
  routes/private/routes/subject.ts
  routes/private/routes/timeline.test.ts
  routes/private/routes/timeline.ts
  routes/private/routes/user.ts
  routes/private/routes/wiki/subject/ep.test.ts
  routes/private/routes/wiki/subject/ep.ts
  routes/private/routes/wiki/subject/image.test.ts
  routes/private/routes/wiki/subject/image.ts
  routes/private/routes/wiki/subject/index.ts
  routes/private/routes/wiki/subject/subject.test.ts
  tests/rest/auth.test.ts
Labels: size/L

#1044 fix: do not allow nsfw only search
  lib/search/character.ts
  lib/search/subject.ts
  lib/types/req.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/search.ts
Labels: size/XS

#1045 fix: timeline progress subject merge
  lib/timeline/writer.ts
Labels: size/XS

#1046 fix: do not check membership for group topic list
  routes/private/routes/group.ts
Labels: size/XS

#1047 bump: 0.14.4
  package.json
Labels: size/XS

#1049 fix: order for group members and topics
  routes/private/routes/group.ts
Labels: size/XS

#1050 feat: add cron to clean access tokens
  bin/cron.ts
  lib/utils/index.ts
  tasks/oauth.ts
Labels: size/S

#1052 fix: add errorHandler for cronjob
  bin/cron.ts
Labels: size/S

#1053 fix: redis zrevrangebyscore command
  tasks/timeline.ts
Labels: size/XS

#1054 fix: do not shift for topic replies
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/group.ts
  routes/private/routes/subject.ts
Labels: size/S

#1055 feat: add func to get user joined group ids
  bin/mq.ts
  event/group.ts
  event/user.ts
  lib/types/res.ts
  lib/user/cache.ts
  lib/user/utils.ts
  routes/__snapshots__/index.test.ts.snap
Labels: size/M

#1056 fix: truncate timeline inbox cache
  tasks/timeline.test.ts
  tasks/timeline.ts
Labels: size/S

#1057 fix: check merge for progress subject timeline
  lib/timeline/writer.test.ts
  lib/timeline/writer.ts
Labels: size/L

#1058 feat: api for recent groups & recent topics
  lib/group/type.ts
  lib/types/req.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/group.test.ts.snap
  routes/private/routes/group.test.ts
  routes/private/routes/group.ts
  routes/private/routes/timeline.ts
  routes/schemas.ts
Labels: size/M

#1066 bump: 0.16.0
  package.json
Labels: size/XS

#1067 fix: sort person works by date
  routes/private/routes/__snapshots__/person.test.ts.snap
  routes/private/routes/person.ts
Labels: size/M

#1069 chore: add more request info to logger
  lib/server.ts
Labels: size/XS

#1070 fix: validate search filters input
  lib/search/subject.ts
Labels: size/S

#1071 fix: incr comment count on new comment created
  lib/comment.ts
Labels: size/S

#1072 bump: 0.16.2
  package.json
Labels: size/XS

#1073 fix: topic response replyCount
  lib/types/convert.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/group.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/group.ts
  routes/private/routes/subject.ts
  routes/schemas.ts
Labels: size/S

#1074 bump: 0.16.3
  package.json
Labels: size/XS

#1075 feat: add api for recent subject topics
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/episode.test.ts
  routes/private/routes/person.test.ts
  routes/private/routes/subject.test.ts
  routes/private/routes/subject.ts
Labels: size/M

#1077 fix: missing group topics response type
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/group.ts
Labels: size/XS

#1076 bump: 0.17.0
  package.json
Labels: size/XS

#1078 feat: add membership to group info
  lib/group/utils.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/group.test.ts.snap
  routes/private/routes/group.test.ts
  routes/private/routes/group.ts
Labels: size/M

#1079 feat: add collectedAt to person & character
  lib/person/type.ts
  lib/person/utils.ts
  lib/subject/type.ts
  routes/private/routes/character.test.ts
  routes/private/routes/character.ts
  routes/private/routes/collection.ts
  routes/private/routes/person.test.ts
  routes/private/routes/person.ts
  routes/private/routes/user.ts
Labels: size/M

#1080 feat: timeline writer support mono
  lib/timeline/item.ts
  lib/timeline/memo.ts
  lib/timeline/type.ts
  lib/timeline/writer.test.ts
  lib/timeline/writer.ts
Labels: size/M

#1081 fix: use code 403 for NotAllowedError
  lib/auth/index.ts
  lib/comment.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/blog.test.ts.snap
  routes/private/routes/__snapshots__/episode.test.ts.snap
  routes/private/routes/__snapshots__/group.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/blog.test.ts
  routes/private/routes/episode.test.ts
  routes/private/routes/group.test.ts
  routes/private/routes/subject.test.ts
  routes/private/routes/wiki/person/index.spec.ts
  routes/private/routes/wiki/subject/subject.test.ts
Labels: size/S

#1087 fix: more conditions for subject tag browsing
  lib/types/fetcher.ts
Labels: size/XS

#1086 fix: do not join users for subject comments
  lib/types/convert.ts
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/subject.test.ts
  routes/private/routes/subject.ts
Labels: size/S

#946 feat: add api for index
  drizzle/orm.ts
  drizzle/schema.ts
  lib/index/cache.ts
  lib/index/types.ts
  lib/openapi/index.ts
  lib/types/common.ts
  lib/types/convert.ts
  lib/types/fetcher.ts
  lib/types/res.ts
  lib/user/stats.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/index.ts
  routes/private/routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
  routes/private/routes/collection.ts
  routes/private/routes/index.test.ts
  routes/private/routes/index.ts
  routes/private/routes/user.ts
  routes/schemas.ts
Labels: size/XL

#1088 fix: always return full episode
  lib/timeline/item.ts
  lib/types/convert.ts
  lib/types/fetcher.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/__snapshots__/timeline.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
  routes/private/routes/episode.ts
  routes/private/routes/index.ts
  routes/private/routes/subject.ts
Labels: size/S

#1092 chore: let pnpm run script in js bash
  .npmrc
Labels: size/XS
