Repository bangumi/server-private, pull requests merged in 2025-01, with the labels that each got.

#921 refactor: migrate wiki ep pushRev to Drizzle
  drizzle/schema.ts
  lib/rev/ep.test.ts
  lib/rev/ep.ts
  routes/private/routes/wiki/subject/ep.ts
Labels: size/M

#929 fix: exclude private collection for user stats
  drizzle/schema.ts
  lib/user/stats.ts
  routes/private/routes/subject.ts
  routes/private/routes/user.ts
Labels: size/XS

#930 fix: group icon urls
  lib/types/convert.ts
  routes/private/routes/__snapshots__/topic.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
Labels: size/XS

#937 feat: make wiki ep pushRev take an array of revisions
  lib/rev/ep.test.ts
  lib/rev/ep.ts
  routes/private/routes/wiki/subject/ep.ts
Labels: size/M

#916 feat: wiki subject new episodes api
  lib/orm/entity/rev.ts
  lib/rev/ep.test.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/wiki/subject/ep.ts
  routes/private/routes/wiki/subject/index.ts
  routes/private/routes/wiki/subject/subject.test.ts
Labels: size/L

#941 feat: add api for subject positions
  lib/types/convert.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/person.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/person.ts
  routes/private/routes/subject.test.ts
  routes/private/routes/subject.ts
  routes/schemas.ts
Labels: size/L

#949 refactor: migrate group/topic/post to drizzle
  drizzle/orm.ts
  drizzle/schema.ts
  lib/error.ts
  lib/group/consts.ts
  lib/group/utils.ts
  lib/openapi/index.ts
  lib/topic/__snapshots__/index.test.ts.snap
  lib/topic/display.ts
  lib/topic/index.test.ts
  lib/topic/index.ts
  lib/topic/state.ts
  lib/topic/type.ts
  lib/topic/utils.ts
  lib/types/convert.ts
  lib/types/fetcher.ts
  lib/types/req.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/index.ts
  routes/private/routes/__snapshots__/group.test.ts.snap
  routes/private/routes/__snapshots__/post.test.ts.snap
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/__snapshots__/topic.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
  routes/private/routes/group.test.ts
  routes/private/routes/group.ts
  routes/private/routes/post.test.ts
  routes/private/routes/post.ts
  routes/private/routes/subject.test.ts
  routes/private/routes/subject.ts
  routes/private/routes/topic.test.ts
  routes/private/routes/topic.ts
  routes/schemas.ts
  tests/graphql/__snapshots__/subject.test.ts.snap
  tests/graphql/subject.test.ts
Labels: size/XXL

#951 feat: api for timeline tsukkomi
  lib/timeline/item.ts
  lib/timeline/type.ts
  lib/types/req.ts
  lib/utils/rate-limit/index.ts
  routes/__snapshots__/index.test.ts.snap
  routes/hooks/rate-limit.ts
  routes/private/routes/episode.ts
  routes/private/routes/timeline.test.ts
  routes/private/routes/timeline.ts
  routes/schemas.ts
Labels: size/M

#943 feat: add reactions to timeline subject collect & subject comments
  lib/__snapshots__/like.test.ts.snap
  lib/like.test.ts
  lib/like.ts
  lib/subject/index.ts
  lib/timeline/item.ts
  lib/timeline/memo.ts
  lib/types/convert.ts
  lib/types/fetcher.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/subject.ts
  routes/private/routes/wiki/subject/image.test.ts
  routes/private/routes/wiki/subject/image.ts
  routes/schemas.ts
Labels: size/M

#952 bump: 0.12.1
  package.json
Labels: size/XS

#953 fix: missing 200 response for update apis
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/episode.ts
  routes/private/routes/group.ts
  routes/private/routes/subject.ts
Labels: size/M

#954 bump: 0.12.2
  package.json
Labels: size/XS

#955 fix: add more fields to profile
  lib/types/convert.ts
  lib/types/examples.ts
  lib/types/req.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
  routes/private/routes/auth.test.ts
  routes/private/routes/auth.ts
  routes/private/routes/episode.test.ts
  routes/private/routes/episode.ts
  routes/private/routes/group.test.ts
  routes/private/routes/group.ts
  routes/private/routes/misc.ts
  routes/private/routes/subject.test.ts
  routes/private/routes/subject.ts
  routes/private/routes/timeline.test.ts
  routes/private/routes/timeline.ts
  routes/schemas.ts
  templates/login.liquid
  tests/rest/auth.test.ts
Labels: size/L

#957 bump: 0.12.3
  package.json
Labels: size/XS

#970 tests: use built-in github actions reporter
  package.json
  pnpm-lock.yaml
  vitest.config.ts
Labels: size/XS
