Repository bangumi/server-private, pull requests merged in 2025-03, with the labels that each got.

#1104 feat: timeline writer add more cat
  lib/timeline/item.ts
  lib/timeline/kafka.ts
  lib/timeline/memo.ts
  lib/timeline/type.ts
  lib/timeline/writer.ts
Labels: size/M

#1106 chore: remove deprecated unicorn rule
  eslint.config.mjs
Labels: size/XS

#1091 feat: add friend apis
  drizzle/orm.ts
  drizzle/schema.ts
  lib/notify.ts
  lib/openapi/index.ts
  lib/types/fetcher.ts
  lib/types/res.ts
  lib/user/utils.ts
  lib/utils/rate-limit/index.ts
  routes/__snapshots__/index.test.ts.snap
  routes/hooks/rate-limit.ts
  routes/private/index.ts
  routes/private/routes/__snapshots__/relationship.test.ts.snap
  routes/private/routes/friend.test.ts
  routes/private/routes/friend.ts
  routes/private/routes/group.ts
  routes/private/routes/misc.test.ts
  routes/private/routes/misc.ts
  routes/private/routes/relationship.test.ts
  routes/private/routes/relationship.ts
  routes/private/routes/subject.ts
  routes/schemas.ts
Labels: size/XXL

#1107 chore: clean some old orm
  lib/graphql/resolvers/subject.ts
  lib/graphql/schema.ts
  lib/orm/entity/app.ts
  lib/orm/entity/group.ts
  lib/orm/entity/index.ts
  lib/orm/entity/notify.ts
  lib/orm/entity/subject.ts
  lib/orm/entity/user.ts
  lib/orm/index.ts
  lib/orm/unused/ChiiCrtComments.ts.tmp
  lib/orm/unused/ChiiEpComments.ts.tmp
  lib/orm/unused/ChiiEpStatus.ts.tmp
  lib/orm/unused/ChiiIndex.ts.tmp
  lib/orm/unused/ChiiIndexCollects.ts.tmp
  lib/orm/unused/ChiiIndexComments.ts.tmp
  lib/orm/unused/ChiiIndexRelated.ts.tmp
  lib/orm/unused/ChiiPersonAlias.ts.tmp
  lib/orm/unused/ChiiPersonCollects.ts.tmp
  lib/orm/unused/ChiiPersonFields.ts.tmp
  lib/orm/unused/ChiiPersonRelationship.ts.tmp
  lib/orm/unused/ChiiPms.ts.tmp
  lib/orm/unused/ChiiPrsnComments.ts.tmp
  lib/orm/unused/ChiiRevHistory.ts.tmp
  lib/orm/unused/ChiiSubjectAlias.ts.tmp
  lib/orm/unused/ChiiSubjectPosts.ts.tmp
  lib/orm/unused/ChiiTimeline.ts.tmp
  routes/hooks/pre-handler.ts
  routes/private/routes/auth.ts
Labels: size/XXL

#1108 feat: add like apis
  drizzle/schema.ts
  lib/comment.ts
  lib/like.test.ts
  lib/like.ts
  lib/subject/index.ts
  lib/timeline/item.ts
  lib/timeline/type.ts
  lib/types/convert.ts
  lib/types/req.ts
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/collection.test.ts.snap
  routes/private/routes/__snapshots__/user.test.ts.snap
  routes/private/routes/episode.ts
  routes/private/routes/group.ts
  routes/private/routes/subject.ts
  routes/private/routes/timeline.ts
  routes/private/routes/wiki/subject/image.test.ts
  routes/private/routes/wiki/subject/image.ts
  routes/schemas.ts
Labels: size/XXL

#1109 chore: add 429 for ratelimit request
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/blog.ts
  routes/private/routes/character.ts
  routes/private/routes/collection.ts
  routes/private/routes/episode.ts
  routes/private/routes/group.ts
  routes/private/routes/person.ts
  routes/private/routes/relationship.ts
  routes/private/routes/subject.ts
  routes/private/routes/timeline.ts
Labels: size/M

#1110 chore: add test for subject collect with progress
  lib/subject/utils.ts
  routes/private/routes/collection.test.ts
  routes/private/routes/collection.ts
  routes/private/routes/subject.ts
Labels: size/S

#1111 bump: 0.19.0
  package.json
Labels: size/XS

#1112 docs: update readme.md
  readme.md
Labels: size/XS

#1115 fix: revert episode watch status
  routes/private/routes/collection.ts
Labels: size/XS

#1117 fix: emthod for group post like
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/group.ts
Labels: size/XS

#1118 bump: 0.19.1
  package.json
Labels: size/XS

#1119 feat: add collection apis
  lib/comment.ts
  lib/like.ts
  lib/subject/index.ts
  lib/types/fetcher.ts
  lib/utils/rate-limit/index.ts
  routes/__snapshots__/index.test.ts.snap
  routes/hooks/rate-limit.ts
  routes/private/routes/collection.ts
  routes/private/routes/subject.ts
  routes/private/routes/timeline.ts
  routes/private/routes/wiki/subject/index.ts
Labels: size/XL

#1121 feat: add api for friendlist
  lib/types/res.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/misc.ts
  routes/private/routes/relationship.ts
Labels: size/M

#1122 bump: 0.20.0
  package.json
Labels: size/XS

#1123 fix: htmlescape more contents
  drizzle/schema.ts
Labels: size/S

#1125 chore: add CODEOWNERS
  .github/CODEOWNERS
Labels: size/XS

#1124 feat: support filter mode in getGroups
  lib/group/type.ts
  lib/types/req.ts
  routes/__snapshots__/index.test.ts.snap
  routes/private/routes/__snapshots__/group.test.ts.snap
  routes/private/routes/group.test.ts
  routes/private/routes/group.ts
  routes/schemas.ts
Labels: size/M

#1127 Update CODEOWNERS
  .github/CODEOWNERS
Labels: size/XS

#1130 fix: subject staff positions
  routes/private/routes/__snapshots__/subject.test.ts.snap
  routes/private/routes/subject.ts
Labels: size/S

#1131 bump: 0.21.1
  package.json
Labels: size/XS

#1144 fix: browse subjects with trends
  lib/types/fetcher.ts
Labels: size/XS

#1146 fix: browse subject filter tags
  lib/types/fetcher.ts
Labels: size/S

#1147 build: patch `fastify-socket.io`
  package.json
  patches/fastify-socket.io.patch
  pnpm-lock.yaml
Labels: size/S

#1149 style: check deprecated
  eslint.config.mjs
  lib/graphql/ui.ts
Labels: size/XS

#1143 refactor: remove some typescript only syntax
  eslint.config.mjs
  event/type.ts
  lib/auth/index.ts
  lib/config.ts
  lib/group/type.ts
  lib/index/types.ts
  lib/like.ts
  lib/notify.ts
  lib/person/type.ts
  lib/subject/type.ts
  lib/subject/utils.ts
  lib/tag.ts
  lib/timeline/item.ts
  lib/timeline/type.ts
  lib/timeline/writer.ts
  lib/topic/state.ts
  lib/topic/type.ts
  lib/trending/type.ts
  lib/types/req.ts
  lib/user/perm.ts
  lib/utils/date.ts
  lib/utils/rate-limit/index.ts
  package.json
  pnpm-lock.yaml
  routes/demo/token/index.ts
  routes/oauth/index.ts
  routes/private/routes/collection.ts
  routes/private/routes/group.ts
  routes/private/routes/subject.ts
  tsconfig.json
  vendor/node-cache.ts
Labels: size/XL

#1155 fix: hide content with abnormal state
  lib/comment.ts
  routes/private/routes/group.ts
Labels: size/XS

#1156 fix: filter subject tags
  lib/types/fetcher.ts
Labels: size/XS

#1160 Update ci.yaml
  .github/workflows/ci.yaml
Labels: size/XS

#1165 Update .gitattributes
  .gitattributes
Labels: size/XS
